//localhost
###

GET http://localhost:8080/events
###
GET http://localhost:8080/events/Memorial Day Party


### CREATE 
POST http://localhost:8080/events HTTP/1.1
content-type: application/json

{
    "eventName": "Memorial Day Party",
    "date": "5/30/2022",
    "eventHost": "Jess",
    "startTime": "5:00 PM",
    "endTime": "8:00 PM",
    "location": "All Star Bowling",
    "comments": "Join us for an awesome party!"
}

### UPDATE
PUT http://localhost:8080/events/Memorial Day Party HTTP/1.1
content-type: application/json

{
    "eventName": "Memorial Day Party",
    "date": "6/3/2022",
    "eventHost": "Tim",
    "startTime": "5:00 PM",
    "endTime": "8:00 PM",
    "location": "All Star Bowling",
    "comments": "Join us for an awesome party!"
}

### DELETE
DELETE http://localhost:8080/events/Memorial Day Party HTTP/1.1

//production

###
GET https://cse341-jm.herokuapp.com/events
###
GET https://cse341-jm.herokuapp.com/events/Memorial Day Party
###
### CREATE CONTACT
POST https://cse341-jm.herokuapp.com/events HTTP/1.1
content-type: application/json

{
    "eventName": "Birthday Party",
    "date": "7/21/2022",
    "eventHost": "Jess",
    "startTime": "5:00 PM",
    "endTime": "8:00 PM",
    "location": "Tim's House",
    "comments": "Join us for an awesome party!"
}

### UPDATE CONTACT
PUT https://cse341-jm.herokuapp.com/events/Birthday Party HTTP/1.1
content-type: application/json

{
    "eventName": "Birthday Party",
    "date": "7/21/2022",
    "eventHost": "Becky",
    "startTime": "7:00 PM",
    "endTime": "8:00 PM",
    "location": "Tim's House",
    "comments": "Join us for an awesome party!"
}

### DELETE CONTACT
DELETE https://cse341-jm.herokuapp.com/events/Birthday Party HTTP/1.1
