//localhost

###
GET http://localhost:8080/events

###
GET http://localhost:8080/location

###
GET http://localhost:8080/events/Memorial Day Party

###
GET http://localhost:8080/location/All Star Bowling


### CREATE 
POST http://localhost:8080/events HTTP/1.1
content-type: application/json

{
    "eventName": "Memorial Day Party",
    "date": "5/30/2022",
    "eventHost": "Jess",
    "startTime": "5:00 PM",
    "endTime": "8:00 PM",
    "location": "All Star Bowling",
    "comments": "Join us for an awesome party!"
}

###
POST http://localhost:8080/events HTTP/1.1
content-type: application/json

{
    "locationName": "Chick-fil-a",
    "streetAddress": "345 N 798 E",
    "city": "Midvale",
    "state": "Utah",
    "zipCode": "84444",
    "webAddress": "https://www.thatlocation.com",
    "phoneNum": "888-657-9764"
}

### UPDATE
PUT http://localhost:8080/events/Memorial Day Party HTTP/1.1
content-type: application/json

{
    "eventName": "Memorial Day Party",
    "date": "6/3/2022",
    "eventHost": "Tim",
    "startTime": "5:00 PM",
    "endTime": "8:00 PM",
    "location": "All Star Bowling",
    "comments": "Join us for an awesome party!"
}

###
PUT http://localhost:8080/location/Chick-fil-a HTTP/1.1
content-type: application/json

{
    "locationName": "Chick-fil-a",
    "streetAddress": "345 N 798 E",
    "city": "Springville",
    "state": "Utah",
    "zipCode": "84444",
    "webAddress": "https://www.thatlocation.com",
    "phoneNum": "888-657-9764"
}

### DELETE
DELETE http://localhost:8080/events/Memorial Day Party HTTP/1.1

###
DELETE http://localhost:8080/location/Chick-fil-a HTTP/1.1

//production

### GET ALL
GET https://event-book-cse341.herokuapp.com/events

###
GET https://event-book-cse341.herokuapp.com/location

### GET ONE
GET https://event-book-cse341.herokuapp.com/location/All Star Bowling

###
GET https://event-book-cse341.herokuapp.com/events/Memorial Day Party

### CREATE
POST https://event-book-cse341.herokuapp.com/events HTTP/1.1
content-type: application/json

{
    "eventName": "Birthday Party",
    "date": "7/21/2022",
    "eventHost": "Jess",
    "startTime": "5:00 PM",
    "endTime": "8:00 PM",
    "location": "Tim's House",
    "comments": "Join us for an awesome party!"
}

### CREATE
POST https://event-book-cse341.herokuapp.com/location HTTP/1.1
content-type: application/json

{
    "locationName": "Chick-fil-a",
    "streetAddress": "345 N 798 E",
    "city": "Midvale",
    "state": "Utah",
    "zipCode": "84444",
    "webAddress": "https://www.thatlocation.com",
    "phoneNum": "756-648-8364"
}

### UPDATE
PUT https://event-book-cse341.herokuapp.com/events/Birthday Party HTTP/1.1
content-type: application/json

{
    "eventName": "Birthday Party",
    "date": "7/21/2022",
    "eventHost": "Becky",
    "startTime": "7:00 PM",
    "endTime": "8:00 PM",
    "location": "Tim's House",
    "comments": "Join us for an awesome party!"
}

### 
PUT https://event-book-cse341.herokuapp.com/location/Chick-fil-a HTTP/1.1
content-type: application/json

{
    "locationName": "Chick-fil-a",
    "streetAddress": "345 N 798 E",
    "city": "Springville",
    "state": "Utah",
    "zipCode": "84444",
    "webAddress": "https://www.thatlocation.com",
    "phoneNum": "888-657-9764"
}

### DELETE
DELETE https://event-book-cse341.herokuapp.com/events/Birthday Party HTTP/1.1

### 
DELETE https://event-book-cse341.herokuapp.com/location/Chick-fil-a HTTP/1.1