//localhost
###

GET http://localhost:8080/users
###
GET http://localhost:8080/users/jess


### CREATE 
POST http://localhost:8080/users HTTP/1.1
content-type: application/json

{
    "user": {
        "username": "NewUser",
        "password": "PassWord",
        "email": "new@gmail.com",
        "events": [
            {
                "eventName": "Memorial Day Party",
                "date": "5/30/2022",
                "startTime": "5:00 PM",
                "endTime": "8:00 PM",
                "location": "All Star Bowling",
                "comments": "Join us for an awesome party!" 
            }
            
        ]
    }
}

### UPDATE
PUT http://localhost:8080/contacts/62689ccf2736de3a1685023d HTTP/1.1
content-type: application/json

{
    "firstName": "Chris",
    "lastName": "Hemsworth",
    "email": "Chris@thor.com",
    "favColor": "Pink",
    "birthday": "08/06/75"
}

### DELETE CONTACT
DELETE http://localhost:8080/contacts/62748913ca6358eb0136b049 HTTP/1.1

//production

###
GET https://cse341-jm.herokuapp.com/contacts
###
GET https://cse341-jm.herokuapp.com/contacts/62689ccf2736de3a1685023b
###
### CREATE CONTACT
POST https://cse341-jm.herokuapp.com/contacts HTTP/1.1
content-type: application/json

{
    "firstName": "Johnny",
    "lastName": "Depp",
    "email": "johnny@depp.com",
    "favColor": "Maroon",
    "birthday": "06/25/84"
}

### UPDATE CONTACT
PUT https://cse341-jm.herokuapp.com/contacts/62689ccf2736de3a1685023d HTTP/1.1
content-type: application/json

{
    "firstName": "Chris",
    "lastName": "Hemsworth",
    "email": "Chris@thor.com",
    "favColor": "Green",
    "birthday": "08/06/75"
}

### DELETE CONTACT
DELETE https://cse341-jm.herokuapp.com/contacts/62748a4dd0576c530b5b5778 HTTP/1.1
